export const pokemons = [
    {
        id:1,
        name:'Bulbasur1',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','psiquico'],
    },
    {
        id:2,
        name:'Bulbasur2',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','madre'],
    },
    {
        id:3,
        name:'Bulbasur3',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','padre'],
    },
    {
        id:4,
        name:'Bulbasur4',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','madre'],
    },
    {
        id:5,
        name:'Bulbasur5',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','padre'],
    },
    {
        id:6,
        name:'Bulbasur6',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','psiquico'],
    },
    {
        id:7,
        name:'Bulbasur7',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','madre'],
    },
    {
        id:8,
        name:'Bulbasur8',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','madre'],
    },
    {
        id:9,
        name:'Bulbasur9',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','padre'],
    },
    {
        id:10,
        name:'Bulbasur10',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','psiquico'],
    },
    {
        id:11,
        name:'Bulbasur11',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','madre'],
    },
    {
        id:12,
        name:'Bulbasur12',
        images:"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
        types:['hierba','psiquico'],
    },

   
  ]